version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pippindb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - pippin-net

  backend:
    build: ./backend
    # Mount backend source for hot-reload during development
    volumes:
      - ./backend:/app
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pippindb
      # Read from host env at runtime.  You can `export OPENAI_API_KEY=sk-...` before running
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET_KEY: "development-secret-key"
      # Optional: Base URL for external REST API calls (used by function-calling)
      EXTERNAL_API_BASE_URL: ${EXTERNAL_API_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    # Run Uvicorn with --reload to auto-restart on code changes
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    networks:
      - pippin-net

  frontend:
    image: node:20-slim
    working_dir: /app
    # Mount frontend source for hot-reload in development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    networks:
      - pippin-net

volumes:
  pgdata:

networks:
  pippin-net:
    driver: bridge
