[project]
name = "opentrons-lab-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
    "pip>=25.1.1",
    "requests>=2.32.4",
]
